[package]
name = "smartWalletSolana2"
version = "0.1.3"
edition = "2021"

[dependencies]
solana-program = "=2.0.5"

[dev-dependencies]
solana-program-test = "~1.10.35"
solana-sdk = "~1.10.35"

[lib]
name = "smartWalletSolana2"
crate-type = ["cdylib", "lib"]
